In [5]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [60]:
import pandas as pd

df = pd.read_csv("../Data/set/digitalSkillsCollection_en.csv")
print(len(df.columns.tolist()))
print(f"Preferred Labels: {df['preferredLabel'][162]}")
print(f"Alternate Labels: {df['altLabels'][162]}")
print(f"Broader Concepts: {df['broaderConceptPT'][162]}")

10
Preferred Labels: Angular
Alternate Labels: Angular related algorithms | testing in Angular | programming paradigms in Angular | coding in Angular | Angular techniques and principles
Broader Concepts: software and applications development and analysis

## Avalible columns

In [8]:
df.columns.tolist()

['conceptType',
 'conceptUri',
 'preferredLabel',
 'status',
 'skillType',
 'reuseLevel',
 'altLabels',
 'description',
 'broaderConceptUri',
 'broaderConceptPT']

### Meaningful data

In [45]:
sub_frame = {
    "preferredLabel": df["preferredLabel"].fillna(''),
    "altLabels": df["altLabels"].fillna('') ,
    "broaderConceptPT": df["broaderConceptPT"].fillna('')
}


skill_df = pd.DataFrame(sub_frame)

labels = ["ASP.NET", "PHP", "Angular", "C++", "Javascript", "Visual Basic"]
labels_lower = [x.lower() for x in labels]
filtered_df = skill_df[skill_df['preferredLabel'].str.lower().isin(labels_lower)]
filtered_df

,preferredLabel,altLabels,broaderConceptPT
109,Visual Basic,VB.NET | .NET | Visual Studio .NET | Visual St...,computer programming | software and applicatio...
162,Angular,Angular related algorithms | testing in Angula...,software and applications development and anal...
286,JavaScript,Client-side JavaScript | Live Script | Escript...,computer programming | software and applicatio...
319,PHP,Hypertext Preprocessor | Personal Home Page,computer programming | software and applicatio...
429,ASP.NET,ASP.NET framework,computer programming | software and applicatio...
907,C++,C++ software | C++ framework,computer programming | software and applicatio...

## Let's try to extract programming languages here

<b>This has less useful information but I will consider it</b>

In [59]:

concepts_lower = [c.lower() for c in ["computer programming"]]


programming_languages = skill_df[
    skill_df['broaderConceptPT']
    .str.split("|")
    .apply(lambda x: any(c.strip().lower() in concepts_lower for c in x) if isinstance(x, list) else False)
]

programming_languages_df = pd.DataFrame(programming_languages)
print(programming_languages_df.shape)
programming_languages_df

(35, 3)

,preferredLabel,altLabels,broaderConceptPT
0,Haskell,Haskell techniques,computer programming | software and applicatio...
10,Erlang,Erlang programming language,computer programming | software and applicatio...
16,SAS language,SAS coding | SAS algorithms | SAS testing | SA...,computer programming | statistical analysis sy...
64,Ruby (computer programming),Ruby,computer programming | software and applicatio...
65,Common Lisp,Common Lisp programming language,computer programming | software and applicatio...
75,Lisp,Lisp software development principles | Lisp al...,computer programming | software and applicatio...
109,Visual Basic,VB.NET | .NET | Visual Studio .NET | Visual St...,computer programming | software and applicatio...
135,Java (computer programming),Java 2 | Java 2 enterprise edition | Java,computer programming | software and applicatio...
224,Prolog (computer programming),Prolog,computer programming | software and applicatio...
237,OpenEdge Advanced Business Language,OpenEdge Advanced Business Language techniques,computer programming | software and applicatio...
286,JavaScript,Client-side JavaScript | Live Script | Escript...,computer programming | software and applicatio...
303,Perl,Practical Extraction and Report Language | PONIE,computer programming | software and applicatio...
317,Smalltalk (computer programming),Smalltalk programming system | Smalltalk,computer programming | software and applicatio...
319,PHP,Hypertext Preprocessor | Personal Home Page,computer programming | software and applicatio...
346,Assembly (computer programming),Assembly computer programming paradigms | Asse...,computer programming | software and applicatio...
368,C#,C Sharp,computer programming | software and applicatio...
402,Groovy,Groovy software techniques | Groovy programmin...,computer programming | software and applicatio...
429,ASP.NET,ASP.NET framework,computer programming | software and applicatio...
441,APL,APL programming paradigms,computer programming | software and applicatio...
521,web programming,markup programming,computer programming | software and applicatio...
677,TypeScript,TypeScript programming language,computer programming | software and applicatio...
763,CoffeeScript,CoffeeScript coding techniques | CoffeeScript ...,computer programming | software and applicatio...
764,Objective-C,Objective C,computer programming | software and applicatio...
823,ML (computer programming),ML | ML systems | ML development principles,computer programming | software and applicatio...
904,AJAX,AJAX technology | AJAX software | AJAX techniques,computer programming | software and applicatio...
907,C++,C++ software | C++ framework,computer programming | software and applicatio...
937,SAP R3,SAP R/3 | SAP R/3 Enterprise Edition | SAP S/4...,computer programming | software and applicatio...
950,Swift (computer programming),Swift programming paradigms | Swift software d...,computer programming | software and applicatio...
978,MATLAB,MATLAB software development principles | MATLA...,computer programming | software and applicatio...
1019,Python (computer programming),Python 3K | Python,computer programming | software and applicatio...
1064,Scratch (computer programming),Scratch,computer programming | software and applicatio...
1101,VBScript,VBScript for web-based scripting | VBScript pr...,computer programming | software and applicatio...
1115,COBOL,COBOL programming language | Cobol | COBOL app...,computer programming | software and applicatio...
1162,Pascal (computer programming),Pascal,computer programming | software and applicatio...
1170,ABAP,ABAP Programming Techniques | ABAP software de...,computer programming | software and applicatio...

## Let's look at something different

In [11]:
import pandas as pd

df = pd.read_csv("../src/Export/programming.csv")

unique_category = df['category'].unique()
print(unique_category)

<StringArray>
['Programming Languages',        'Web Frameworks',    'Mobile Development',
             'Databases',        'DevOps & Cloud', 'Machine Learning & AI',
 'Networking & Security',          'Testing & QA', 'Development Practices']
Length: 9, dtype: str